[package]
name = "toritroubleshooter"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
online = "4.0.2"
reqwest = { version = "0.11", features = ["blocking"] }
spinners = "4.1.1"
tokio = { version = "1", features = ["full"] }
